In [1]:
# 파이썬 버전 확인
import sys
sys.version   # shift + enter : 셀 실행 명령

'3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]'

### 주피터 노트북 필수 단축키
- shift + enter : 셀 실행 후 다음 셀로 이동
- alt + enter : 셀 실행 후 다음에 셀을 추가
- ctrl + '/' : 주석문 설정/해제
- Tab : 들여 쓰기
- shift + Tab : 들여 쓰기 해제



### 파이썬 리스트(List) 
: 가변형(mutable), 시퀀스(str, list, tuple)=[+,*,중첩대입, ], 가장 유용한 자료형, [ ] :대괄호, 중복 허용

In [ ]:
a = [1,2,3,4,5,6]
print(a)
print(type(a))

b = ['a','hello',1,3.5,a,3.5,1]
print(b)

In [ ]:
# 인덱싱
a = [1,2,3,4,5,6]
print(a[0],a[1],a[2],a[3],a[4],a[5],a[-1],a[-2], a[True],a[False]) # True :1과 호환,False : 0과 호환

a[0] = 10   # 가변형이므로 요소 변경이 가능하다
print(a)

In [ ]:
# 슬라이싱 : a[start:end + 1:step]
a = [1,2,3,4,5,6]
print(a[0:1])  # from index 0 to index 2
print(a[:3])   # 시작 인덱스 생략가능
print(a[2:5])  # from index 2 to index 4
print(a[2:])   # 끝 인덱스 생략가능
print(a[:])    # print(a) 와 동일

print(a[::3])  # step을 3으로
print(a[::-1]) # 요소의 순서를 거꾸로 변경한다

In [3]:
# ! pip install numpy
# https://scipy.org
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)
print(type(a))  # <class 'numpy.ndarray'>
print(a.dtype)  # int32

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


### 넘파이(NumPy) : 배열(ndarray, n dimension array)
* 리스트(list) : Linked List구조(불연속), 동작 속도가 느리다, comma로 요소구별, 서로 다른 자료형 사용가능 
* 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소 구별,오직 한 가지 타입만 갖을 수 있다 

In [2]:
# numpy 의 dtype 객체의 종류: 대소문자 모두 사용가능
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'complex64', 'c8', 'complex128', 'c16', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'bool', 'ob

In [4]:
# np.arange(start,end+1,step)
a = np.arange(10)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


### 차원(dimension, Rank) 과 Shape
* 차원(Dimension, Rank) : 1,2,3 차원 , n 차원, 첫 데이터까지의 대괄호의 갯수
* Shape : 차원의 요소의 수, 튜플 형식
#### 1차원 Shape : (x,)
#### 2차원 Shape : (x,y)  , 행렬(matrix)
#### 3차원 Shape : (x,y,z) , (면,행,열)
...
#### n차원 Shape : (x,y,z,....)

In [ ]:
# 1차원의 배열의 Shape
a = np.arange(12)
print(a,type(a))
print(a.shape)  # (12,)  ----> 1차원
t = a.shape
print(type(t))
print((a.shape)[0])

In [ ]:
# 2차원 배열의 Shape : 행(row,가로,수직,axis = 0) 과 열(column,세로,수평,axis =1)  ==> 필수 암기
m = np.array([[0,1,2],
              [0,1,2]])
print(m)
print(m.shape)   # (2,3)  --> 2차원 , 행렬(matrix)
print(m.shape[0], m.shape[1])

In [ ]:
# 3차원 배열의 Shape : (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m)
print(m.shape)  # (2,2,3) ---> 3차원
print(m.shape[0],m.shape[1],m.shape[2])

### 배열의 shape 바꾸기 : reshape() 함수

In [ ]:
m1 = np.arange(12)
print(m1)
print(m1.shape)  # (12,)

m2 = m1.reshape(3,4)
print(m2,m2.shape)  # (3, 4)

m2 = m1.reshape(4,3)
print(m2,m2.shape)  # (4, 3)

m2 = m1.reshape(2,6)
print(m2,m2.shape)  # (2, 6)

m2 = m1.reshape(12,1)
print(m2,m2.shape)  # (12, 1)

In [ ]:
m3 = m1.reshape(2,2,3)
print(m3,m3.shape)

In [ ]:
m4 = m1.reshape(3,2,1,2)
print(m4,m4.shape)

In [ ]:
# -1 을 사용한 reshape  : 요소수를 자동으로 계산
m1 = np.arange(12)
print(m1)
print(m1.shape)  # (12,)

m2 = m1.reshape(-1,6)  # 행의 요소수를 자동으로 계산(알아서 계산해서 만들어줌), 2
print(m2,m2.shape)

m2 = m1.reshape(4,-1)  # 열의 요소수를 자동으로 계산, 3
print(m2,m2.shape)

### 배열의 인덱싱과 슬라이싱

In [3]:
# 1차원 배열의 인덱싱과 슬라이싱 : list 와 동일한 방법
d = np.arange(12)
print(d,d.shape)  # (12,)

print(d[0],d[1],d[2],d[3],d[-1])

print(d[2:8],d[:],d[:-1])
print(d[::2], d[::-1])   # step을 -1로 하면 요소의 순서를 거꾸로 변경한다

d[0] = 10   # list 처럼 요소 변경이 가능
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1 2 3 11
[2 3 4 5 6 7] [ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10] [11 10  9  8  7  6  5  4  3  2  1  0]
[10  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# 2차원 배열의 인덱싱과 슬라이싱 
# data[행,열]
d = np.arange(12).reshape(3,4)
print(d,d.shape)

# 인덱싱
print(d[0][0])  # 0
print(d[0,0])   # 0
print(d[2,1])   # 9

# 슬라이싱
print(d[0])     # [0 1 2 3]
print(d[0,:])   # [0 1 2 3]

print(d[:,:-1])  # (3,3) , 마지막 열(컬럼)을 제외
print(d[:,1:])   # (3,3) , 첫번째 열(컬럼)을 제외
print(d[::2,::2])

d[0] = 20   # 0번 행의 모든 요소를 20으로 변경
print(d)

d[::2,::3] = 30    # 슬라이싱 된 요소 전체를 한번에 변경할 수 있다
print(d)

d[:,:] = -1        # 전체 요소를 한번에 변경할 수 있다
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
0
9
[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 0  2]
 [ 8 10]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [ ]:
# 3차원 배열의 인덱싱과 슬라이싱
# data[면,행,열]
d = np.arange(12).reshape(2,2,3)
print(d,d.shape)

# 인덱싱
print(d[0][0][0])  # 0 old style
print(d[0,0,0])    # 0
print(d[0,1,2])    # 5

# 슬라이싱
print(d[:,:-1,:-1])  # (2,1,2)
print(d[:,1:,1:])    # (2,1,2)
print(d[:,-1,-1])    # (2,)
print(d[:,:,-1])     # (2,2)

In [ ]:
# 인덱싱 결과는 scalar
# 슬라이싱 결과는 ndarray
a = np.arange(12)
print(a,a.shape)

print(a[0])    # 0, scalar
print(a[0:1])  # [0] , 배열(ndarray)

### 불린 인덱싱 : 조건식을 사용한 인덱싱, 조건 검색 필터를 사용한 추출(매우 중요)

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)

print(a > 2)
print(a[a > 2]) # 배열 a에서 2보다 큰 요소를 추출, 결과는 배열
# print(a[[False, False,  True,  True,  True,  True]])

boolean_index = np.array([True,False,True,False,True,True])
print(boolean_index)
print(a[boolean_index])

print(a[a!=3])               # 배열 a에서 3이 아닌 요소를 추출
print(a[(a > 2) & (a < 6)])  # 배열 a에서 2보다 크고 6보다 작은 요소를 추출
print(a[a % 2 == 0])         # 2의 배수(짝수)를 추출
print(a[a < a.mean()])       # 평균보다 작은 값을 추출

In [ ]:
# 배열의 형상 다루기 : reshape(), flatten()(편평화),transpose()(전치)

# flatten() : 다차원 배열을 1차원으로 만든다
a = np.arange(12).reshape(3,4)
print(a,a.shape)

f = a.flatten()      # (3,4)  ----> (12,)
print(f,f.shape)

# 데이터 순서를 거꾸로 변경
print(a[::-1])       # 행의 순서를 거꾸로 변경
print(a[:,::-1])     # 열의 순서를 거꾸로 변경
print(a[::-1,::-1])  # 행과 열의 순서를 거꾸로 변경
print('-'*20)

# transpose() : 전치 행렬 , 행과 열을 서로 맞바꾸는 함수
t = a.transpose()
print(t,t.shape)    # (3,4)  ---> (4,3)   , (x,y) --> (y,x)
print(a.T)          # transpose()함수와 동일한 결과


# 임시로 1차원으로 변경하여 데우터를 채우고 다시 원래의 shape을 갖는다
# 배열의 요소 전체를 한번에 초기화 할때 사용
a.flat = 0
print(a)

### numpy 의 속성(Attribute) : 멤버변수,메서드
#### dtype, shape, ndim, flat, T, size, nbytes

In [ ]:
d = np.arange(12).reshape(3,4)
print(d,d.shape)
print(d.dtype)  # int32 or int64
print(d.ndim)   # 2차원  ==> print(len(d.shape)) 와 동일
print(d.T)      # transpose()함수와 동일한 결과, 전치행렬
print(d.size)   # 12개 , 요소의 갯수
print(d.nbytes) # 48 bytes : 32bit(4 byte) * 12 
d.flat = 1
print(d)

In [ ]:
# numpy 통계 함수들
a = np.arange(12).reshape(3,4)
print(a,a.shape)

print(a.max())    # 최대값
print(np.max(a))

print(a.min())    # 최소값
print(np.min(a))

print(a.sum())    # 합
print(a.mean())   # 평균

print(a.std())    # 표준 편차    
print(a.var())    # 분산
print(np.median(a))  # 중위수

# 사분위수
print('25%:',np.percentile(a,25)) # 1사분위수(Q1)
print('50%:',np.percentile(a,50)) # 2사분위수(Q2), median()과 같은 값
print('75%:',np.percentile(a,75)) # 3사분위수(Q3)